<a href="https://colab.research.google.com/github/UtkarshR8j/PyBasics/blob/master/Arrays_and_Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Arrays are like lists , but they are needed ti be declared , while lists don't .
# Also Arrays are more efficient and allow greater range of data manipulation
# there are two ways of using arrays - using array module in Python or via Numpy


In [ ]:
import array

arr1 =array.array('i',[1,2,3,4])    # syntax : array.array("datatype",list)
arr2 =array.array('d',[1,2,3,4])


print(arr1,"\t",arr2)


array('i', [1, 2, 3, 4]) 	 array('d', [1.0, 2.0, 3.0, 4.0])


In [ ]:
arr1 =array.array('i',[1,2.887,3.66,4.096])
# cannot contain different datatypes 

TypeError: integer argument expected, got float

In [ ]:
# Numpy arrays can contain elements of multiple datatypes , 
import numpy as np

a1 = np.array([3.14, 4, 2, 3])


In [ ]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[9, 7, 4],
       [0, 2, 0],
       [6, 1, 8]])

In [ ]:
# Create a 3x3 identity matrix
np.eye(3)

# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1.44191289e-311, 0.00000000e+000, 6.35806278e+151])